# Generated by Django 2.2 on 2020-10-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ambulance',
        ),
    ]
