# Generated by Django 2.2 on 2020-10-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_delete_ambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
