# Generated by Django 2.2 on 2020-10-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_labtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
