# Generated by Django 2.2 on 2020-10-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ambulance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ambulance',
        ),
    ]
